### ISSUE TITLE
400 Error - config?

### ISSUE THREAD

**Issue by plukevdh** [trydionel/git-pivotal#20]
Anytime I try to use any of the commands (info/feature/etc...) I'm getting the following error.

Expect it has something missing in my config or undocumented configurations needed on the PT side.

Would this be a result of having SSL always enabled?

```
/Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/rest-client-1.6.1/lib/restclient/abstract_response.rb:48:in `return!': 400 Bad Request (RestClient::BadRequest)
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/rest-client-1.6.1/lib/restclient/request.rb:220:in `process_result'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/rest-client-1.6.1/lib/restclient/request.rb:169:in `block in transmit'
    from /Users/hungerandthirst/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:627:in `start'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/rest-client-1.6.1/lib/restclient/request.rb:166:in `transmit'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/rest-client-1.6.1/lib/restclient/request.rb:60:in `execute'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/rest-client-1.6.1/lib/restclient/request.rb:31:in `execute'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/rest-client-1.6.1/lib/restclient/resource.rb:51:in `get'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/pivotal-tracker-0.3.1/lib/pivotal-tracker/project.rb:14:in `find'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/git-pivotal-0.8.0/lib/commands/base.rb:51:in `project'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/git-pivotal-0.8.0/lib/commands/info.rb:28:in `story'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/git-pivotal-0.8.0/lib/commands/info.rb:14:in `run!'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/gems/git-pivotal-0.8.0/bin/git-info:7:in `<top (required)>'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/bin/git-info:19:in `load'
    from /Users/hungerandthirst/.rvm/gems/ruby-1.9.2-p180/bin/git-info:19:in `<main>'
```

**Comment by plukevdh** [comment]
Looks like an issue between PivotalTracker gem and PT API: https://github.com/jsmestad/pivotal-tracker/issues/28

**Comment by plukevdh** [comment]
Actually I take it back. Looks like it its because I have SSL and the initial config is not using SSL.

**Comment by trydionel** [comment]
Hey plukevdh!

So then everything is working properly for you? I'd like to close this ticket if so.

On a related note, I'm considering adding a `setup` or `config` sort of task to aid in getting a project up and rolling, and possibly verify that the given configuration works will with PT. I'll open another ticket for discussion on that -- please join in!

Jeff

**Comment by plukevdh** [comment]
That would help. Its definitely related to SSL. I've got a patch in the works for this.

**Comment by pmbekwa** [comment]
I am getting this error too. I do not think its about using ssl. Well, I am not using ssl. Any ideas please ?

**Comment by pmbekwa** [comment]
My bad.

Add this option on your git/config

[pivotal]
use-ssl = true
