### ISSUE TITLE
git feature fails on ree-1.8.7

### ISSUE THREAD

**Issue by benlangfeld** [trydionel/git-pivotal#8]
The following occurs on ree-1.8.7 but not on ruby-1.9.2-preview3:

```
Updating feature status in Pivotal Tracker...
/Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/git-pivotal-0.2.2/bin/../lib/pivotal/base.rb:29: warning: multiple values for a block parameter (2 for 1)
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/request.rb:218
/Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/git-pivotal-0.2.2/bin/../lib/pivotal/base.rb:30:in `update_attributes': undefined method `code' for #<Array:0x101239a18> (NoMethodError)
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/request.rb:218:in `call'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/request.rb:218:in `process_result'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/request.rb:169:in `transmit'
from /Users/ben/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/net/http.rb:543:in `start'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/request.rb:166:in `transmit'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/request.rb:60:in `execute'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/request.rb:31:in `execute'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/rest-client-1.6.0/lib/restclient/resource.rb:72:in `put'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/git-pivotal-0.2.2/bin/../lib/pivotal/base.rb:29:in `update_attributes'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/git-pivotal-0.2.2/bin/../lib/pivotal/story.rb:11:in `start!'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/git-pivotal-0.2.2/bin/../lib/commands/pick.rb:36:in `run!'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/gems/git-pivotal-0.2.2/bin/git-feature:8
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/bin/git-feature:19:in `load'
from /Users/ben/.rvm/gems/ree-1.8.7-2010.02@studiotalker/bin/git-feature:19
```

**Comment by trydionel** [comment]
Hey Ben,

I think this issue is related to the variance between RestClient versions rather than the Ruby environment.  (I'm guessing that you have rest-client 1.4 in your 1.9.2 install.)  I've tightened git-pivotal's requirements around this dependency in the v0.2.3 release, which should solve your issue.  Please let me know if you're still having trouble after upgrading.

Thanks!
Jeff

**Comment by benlangfeld** [comment]
Works fine now, cheers!
